import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

// Build base app URL once, trimming any trailing slash.
// Falls back to http://localhost:3000 for local dev.
const APP_URL = (
  process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'
).replace(/\/+$/, '');

export async function sendMagicLink(to: string, link: string) {
  console.log('[sendMagicLink] Sending to:', to);
  console.log('[sendMagicLink] Link:', link);

  const response = await resend.emails.send({
    from: process.env.EMAIL_FROM!,
    to,
    subject: 'Confirm your email',
    html: `<p>Click here to log in: <a href="${link}">${link}</a></p>`,
  });

  console.log('[sendMagicLink] Resend API response:', response);
}

/**
 * Send a team invite email that routes the user to /accept-invite
 * where they can set their password. The token should be generated by your invite API.
 *
 * Usage:
 *   await sendInviteEmail({
 *     to: 'new.user@example.com',
 *     token: inviteToken,            // e.g. a signed JWT or opaque token
 *     companyName: 'Acme Ltd'        // optional, for nicer copy
 *   });
 */
export async function sendInviteEmail(params: {
  to: string;
  token: string;
  companyName?: string;
}) {
  const { to, token, companyName } = params;

  const link = `${APP_URL}/accept-invite?token=${encodeURIComponent(token)}`;

  console.log('[sendInviteEmail] Sending to:', to);
  console.log('[sendInviteEmail] Link:', link);

  const subject = companyName
    ? `You're invited to join ${companyName}`
    : 'You’re invited to join';

  const html = `
    <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;line-height:1.6;color:#0f172a">
      <p style="margin:0 0 12px">
        You’ve been invited${companyName ? ` to join <strong>${escapeHtml(companyName)}</strong>` : ''}.
      </p>
      <p style="margin:0 0 20px">Click the button below to accept the invite and set your password.</p>
      <p style="margin:0 0 20px">
        <a href="${link}" style="display:inline-block;padding:12px 18px;border-radius:8px;background:#111827;color:#fff;text-decoration:none;font-weight:600">
          Accept invite
        </a>
      </p>
      <p style="margin:0 0 8px">Or paste this link into your browser:</p>
      <p style="margin:0 0 20px;color:#334155">${link}</p>
      <p style="margin:0;color:#64748b;font-size:12px">If you didn’t expect this invitation, you can safely ignore this email.</p>
    </div>
  `.trim();

  const response = await resend.emails.send({
    from: process.env.EMAIL_FROM!,
    to,
    subject,
    html,
  });

  console.log('[sendInviteEmail] Resend API response:', response);
}

// --- helpers ---
function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
