name: CI

on:
  push:
    branches: [main, dev/auth-addition]
  pull_request:
    branches: [main, dev/auth-addition]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies using Yarn workspaces
        run: yarn install --frozen-lockfile

      - name: Build all workspaces
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Run tests
        run: yarn test
