name: CI

on:
  push:
    branches: [main, dev/auth-addition]
  pull_request:
    branches: [main, dev/auth-addition]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies using npm
        run: npm ci

      - name: Build all workspaces
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test
