name: CI

on:
  push:
    branches:
      - main
      - dev/auth-addition
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      NEXTAUTH_URL:         ${{ secrets.NEXTAUTH_URL }}
      RESEND_API_KEY:       ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM:           ${{ secrets.EMAIL_FROM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Format & Lint
        run: |
          npm run format
          npm run lint

      - name: Build Auth Package
        run: npm --prefix packages/auth run build

      - name: Build Next.js App
        run: next build

      - name: Run tests
        run: npm test -- --runInBand
