name: CI

on:
  push:
    branches: [main, dev/auth-addition]
  pull_request:
    branches: [main, dev/auth-addition]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      NEXTAUTH_URL:       ${{ secrets.NEXTAUTH_URL }}
      RESEND_API_KEY:     ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM:         ${{ secrets.EMAIL_FROM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies using npm
        run: npm ci

      - name: Build all workspaces
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test
