name: CI

on:
  push:
    branches:
      - '**'          # run CI on all branches
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: '1'
      HUSKY: '0' 
      # Secrets required by build (lazy-read at runtime too, but present here keeps SSR/imports happy)
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXTAUTH_URL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            **/.next/cache
          key: next-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            next-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npm run typecheck --if-present

      - name: Test
        run: npm test --if-present
